---
name: On PR

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  platformio-build:
    uses: ./.github/workflows/job-platformio-build.yml